language: c
before_install:
  - sudo apt-get install -yy qemu-system-mips expect
  - wget --no-check-certificate -O gcc.tgz 'https://www.mips.com/?do-download=linux-x64-mti-bare-metal-2016-05-06'
  - tar -xf gcc.tgz

script:
  - "export PATH=$PATH:$PWD/mips-mti-elf/2016.05-06/bin"
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y EN_INT=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y EN_INT=y EN_TLB=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n EN_INT=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n EN_INT=y EN_TLB=y -C kernel/ clean all
  - travis_wait 1 make sim -C kernel || true
  - ./.test-script

addons:
  apt:
    update: true
