language: c
before_install:
  - sudo apt-get install -yy qemu-system-mips expect
  - curl -sc /tmp/gcokie 'https://drive.google.com/uc?export=download&id=1Mo5hGcCg1zm8Ca0KQB-G5PNI3fXfAAmR'
  - getcode="$(awk '/_warning_/ {print $NF}' /tmp/gcokie)"
  - curl -s -C - -LOJb /tmp/gcokie "https://drive.google.com/uc?export=download&confirm=${getcode}&id=1Mo5hGcCg1zm8Ca0KQB-G5PNI3fXfAAmR"
  - tar -xf Codescape.GNU.Tools.Package.2016.05-06.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz

script:
  - "export PATH=$PATH:$PWD/mips-mti-elf/2016.05-06/bin"
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y EN_INT=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y EN_INT=y EN_TLB=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n EN_INT=y -C kernel/ clean all
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n EN_INT=y EN_TLB=y -C kernel/ clean all
  - travis_wait 1 make sim -C kernel || true
  - ./.test-script

addons:
  apt:
    update: true
