language: c
sudo: false
before_install:
  # - wget --no-check-certificate -O gcc.tgz 'https://www.mips.com/?do-download=linux-x64-mti-bare-metal-2016-05-06'
  - wget --no-check-certificate -O gcc.tgz 'https://drive.google.com/uc?export=download&id=1Mo5hGcCg1zm8Ca0KQB-G5PNI3fXfAAmR'
  - tar -xf gcc.tgz

script:
  - make GCCPREFIX=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- -C kernel/ clean all
  - make GCCPREFIX=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- EN_INT=y -C kernel/ clean all
  - make GCCPREFIX=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- EN_INT=y EN_TLB=y -C kernel/ clean all

addons:
  apt:
    update: true
